### PR TITLE
Add permanent axis display option + display all mesh types

### PR DESCRIPTION
**Pull request by Gorgious56**
I thought it would be a nice exercise to try and add functionality to your very nice work. I hope you're okay with that, I tried not to change things outside of the new file too much. I tried to optimise redundant code in the verts selection part but I may have missed things.

It adds a permanent handler and a toggle in the addon panel to display colored wires for every selected object in any mode

Supports Curves, Meta objects, surfaces, texts

image

Toggle on or off with a button in the interface.

image

capture

### CODE REVIEW

**Comment by brunoperdigao** [comment]
Hi @Gorgious56, thank you so much for your contribution, it's a great improvement! I'll take a look at the code soon, I'm pretty sure I'll learn a lot.

**Comment by Gorgious56** [comment]
Nice ! Don't hesitate to ask questions or for clarifications, I didn't comment the code but it's basically the same principle as your script, just extended for object mode and other object types. :) First time I worked with gpu shaders and I found it's actually not that complicated once you get the gist of it.

Cheers !

**Comment by brunoperdigao** [comment]
Hi @Gorgious56 sorry I took too long. I merged your PR. I am planning on removing the operator and using just the property as you proposed. And maybe changing the toggle to a checkbox, that way it will resemble the UI of the default overlays in Blender.

**Comment by Gorgious56** [comment]
@brunoperdigao  Awesome ! Let me know if you need any further information about the code :)

**Pull request merged**
